import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { ArrowLeft, AlertCircle } from "lucide-react";
import logoUrl from "@/assets/ai-focus-logo.png";
import { ThemeToggle } from "@/components/ThemeToggle";

const FAQ = () => {
  return (
    <div className="min-h-screen flex flex-col">
      {/* Header */}
      <header className="border-b border-white/10 sticky top-0 z-50 shadow-md" style={{ backgroundColor: 'hsl(208, 57%, 21%)' }}>
        <div className="container mx-auto px-4 py-6 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-6 hover:opacity-90 transition-opacity">
            <img src={logoUrl} alt="AI-Focus Logo" className="h-16 w-16" />
            <div>
              <h1 className="text-3xl font-bold text-white">MilesFocus</h1>
              <p className="text-sm text-white/80">by AI-Focus Technologies</p>
            </div>
          </Link>
          <div className="flex items-center gap-3">
            <ThemeToggle variant="header" />
            <Link to="/app">
              <Button size="lg" className="bg-white text-primary hover:bg-white/90">Get Started</Button>
            </Link>
          </div>
        </div>
      </header>

      {/* Content */}
      <main className="flex-1 container mx-auto px-4 py-12 max-w-4xl">
        <Link to="/" className="inline-flex items-center text-primary hover:underline mb-6">
          <ArrowLeft className="h-4 w-4 mr-2" />
          Back to Home
        </Link>

        <h1 className="text-4xl font-bold mb-4">FAQ – MilesFocus & Mileage Tracking</h1>
        <p className="text-lg text-muted-foreground mb-8">
          Common questions about how MilesFocus works and what it can (and cannot) do for your mileage tracking needs.
        </p>

        <Accordion type="single" collapsible className="space-y-4">
          <AccordionItem value="item-1" className="border rounded-lg px-6">
            <AccordionTrigger className="text-left font-semibold">
              What does MilesFocus actually do?
            </AccordionTrigger>
            <AccordionContent className="text-muted-foreground">
              MilesFocus helps you turn your Google Maps Timeline data into a clean mileage log and summary.
              You upload your Timeline JSON, review your trips, tag them by purpose (e.g., Business, Personal, Medical, Charitable), 
              and export a detailed report in Excel or PDF format.
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="item-2" className="border rounded-lg px-6">
            <AccordionTrigger className="text-left font-semibold">
              Does MilesFocus give me tax advice?
            </AccordionTrigger>
            <AccordionContent className="text-muted-foreground">
              <strong>No.</strong> MilesFocus does not provide tax, legal, or financial advice.
              It simply organizes your mileage data and shows estimated values based on publicly available IRS mileage rates. 
              For questions about what you can actually claim on your tax return, please talk to a qualified tax professional or accountant.
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="item-3" className="border rounded-lg px-6">
            <AccordionTrigger className="text-left font-semibold">
              Is the "Estimated Deduction" the exact amount I can write off?
            </AccordionTrigger>
            <AccordionContent className="text-muted-foreground">
              <strong>No.</strong> Any "Estimated Deduction" shown in MilesFocus is a rough calculation based on the miles you mark as Business 
              and the standard mileage rate for the year. It does not account for your full tax situation, limits, or other IRS rules.
              Think of it as a helpful reference, not a final number to file with.
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="item-4" className="border rounded-lg px-6">
            <AccordionTrigger className="text-left font-semibold">
              Does the IRS accept reports generated by MilesFocus?
            </AccordionTrigger>
            <AccordionContent className="text-muted-foreground">
              The IRS does not "approve" or "certify" third-party tools. However, the information that MilesFocus helps you organize—dates, 
              mileage, and trip purposes—is aligned with the kinds of records the IRS generally expects taxpayers to maintain. 
              Ultimately, it's your responsibility to keep accurate records and use them correctly on your tax return.
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="item-5" className="border rounded-lg px-6">
            <AccordionTrigger className="text-left font-semibold">
              Where does MilesFocus get its mileage rates from?
            </AccordionTrigger>
            <AccordionContent className="text-muted-foreground">
              MilesFocus uses the publicly published IRS Standard Mileage Rates for each year (for example, separate rates for business, 
              medical, moving, and charitable miles). These rates are published by the IRS in official notices. When a new year's rates 
              are released, they can be updated in the app configuration.
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="item-6" className="border rounded-lg px-6">
            <AccordionTrigger className="text-left font-semibold">
              What data from my Google Timeline does MilesFocus use?
            </AccordionTrigger>
            <AccordionContent className="text-muted-foreground">
              MilesFocus uses only the parts of your Timeline export that relate to movement/activities, such as "in passenger vehicle" 
              segments and their associated distances. It does not need or use your search history, reviews, or other unrelated activity. 
              You stay in control because you choose what file to upload.
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="item-7" className="border rounded-lg px-6">
            <AccordionTrigger className="text-left font-semibold">
              Does MilesFocus store my data?
            </AccordionTrigger>
            <AccordionContent className="text-muted-foreground">
              By default, MilesFocus processes your data in memory for the current session. If you deploy or host the app yourself, 
              you control where it runs and how logs are stored. If you later run a hosted SaaS version, please review that service's 
              specific privacy and data-retention policies.
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="item-8" className="border rounded-lg px-6">
            <AccordionTrigger className="text-left font-semibold">
              Can I use MilesFocus for both personal and business mileage?
            </AccordionTrigger>
            <AccordionContent className="text-muted-foreground">
              Yes. You can classify trips as Business, Personal, Medical, Charitable, or Other. Only your own categorization and your 
              tax advisor can determine what actually qualifies for tax purposes.
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="item-9" className="border rounded-lg px-6">
            <AccordionTrigger className="text-left font-semibold">
              Do I still need to talk to a tax professional?
            </AccordionTrigger>
            <AccordionContent className="text-muted-foreground">
              <strong>Yes, strongly recommended.</strong> MilesFocus is a tool to help you organize mileage. A tax professional can help 
              you interpret the rules correctly, decide which method to use (standard mileage vs. actual expenses), and file your return properly.
            </AccordionContent>
          </AccordionItem>
        </Accordion>

        {/* Disclaimer */}
        <div className="mt-12 p-6 bg-muted/50 border rounded-lg flex items-start gap-3">
          <AlertCircle className="h-5 w-5 text-muted-foreground mt-0.5 flex-shrink-0" />
          <div className="text-sm text-muted-foreground">
            <p className="font-semibold text-foreground mb-2">Disclaimer</p>
            <p>
              MilesFocus organizes mileage data and provides calculations based on publicly available IRS mileage rates.
              It does not provide tax, legal, or financial advice. All deduction amounts shown are estimates only.
              Please consult a qualified tax professional for guidance specific to your situation.
            </p>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-card/50 border-t py-8 px-4 mt-12 backdrop-blur-sm">
        <div className="container mx-auto text-center text-sm text-muted-foreground">
          <p>
            © {new Date().getFullYear()}{" "}
            <a 
              href="https://www.ai-focus.org" 
              target="_blank" 
              rel="noopener noreferrer"
              className="hover:text-primary transition-colors underline"
            >
              AI-Focus Technologies
            </a>
            . All rights reserved. Built by{" "}
            <a 
              href="https://www.sujitg.com" 
              target="_blank" 
              rel="noopener noreferrer"
              className="hover:text-primary transition-colors underline"
            >
              Sujit Gangadharan
            </a>
          </p>
        </div>
      </footer>
    </div>
  );
};

export default FAQ;
