import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { NormalizedTrip, MonthlySummary } from "@/types/trip";

export function exportToPDF(trips: NormalizedTrip[], summaries: MonthlySummary[], month: string) {
  const doc = new jsPDF();
  
  // AI-Focus brand colors
  const navyBlue: [number, number, number] = [21, 49, 77]; // #15314D
  const grey: [number, number, number] = [145, 156, 167]; // #919CA7
  const darkGrey: [number, number, number] = [64, 64, 64]; // #404040
  
  // Header with logo placeholder
  doc.setFillColor(navyBlue[0], navyBlue[1], navyBlue[2]);
  doc.rect(0, 0, 220, 30, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.text("MilesFocus", 15, 15);
  
  doc.setFontSize(10);
  doc.text("AI-Focus Technologies", 15, 22);
  
  // Title
  doc.setTextColor(navyBlue[0], navyBlue[1], navyBlue[2]);
  doc.setFontSize(16);
  const monthDisplay = month || "All Months";
  doc.text(`Mileage Log - ${monthDisplay}`, 15, 45);
  
  // Filter trips by month if specified
  let filteredTrips = trips;
  if (month && month !== "all") {
    filteredTrips = trips.filter(t => t.date.startsWith(month));
  }
  
  // Get summary for this month
  const summary = summaries.find(s => s.month === month) || {
    businessMiles: 0,
    personalMiles: 0,
    medicalMiles: 0,
    charitableMiles: 0,
    otherMiles: 0,
    totalMiles: 0,
  };
  
  // Monthly Summary Box
  doc.setFontSize(12);
  doc.setTextColor(navyBlue[0], navyBlue[1], navyBlue[2]);
  doc.text("Monthly Summary", 15, 55);
  
  doc.setFontSize(10);
  doc.setTextColor(darkGrey[0], darkGrey[1], darkGrey[2]);
  let yPos = 62;
  doc.text(`Business Miles: ${summary.businessMiles.toFixed(2)}`, 15, yPos);
  yPos += 6;
  doc.text(`Personal Miles: ${summary.personalMiles.toFixed(2)}`, 15, yPos);
  yPos += 6;
  doc.text(`Medical Miles: ${summary.medicalMiles.toFixed(2)}`, 15, yPos);
  yPos += 6;
  doc.text(`Charitable Miles: ${summary.charitableMiles.toFixed(2)}`, 15, yPos);
  yPos += 6;
  doc.text(`Other Miles: ${summary.otherMiles.toFixed(2)}`, 15, yPos);
  yPos += 6;
  doc.setFont(undefined, 'bold');
  doc.text(`Total Miles: ${summary.totalMiles.toFixed(2)}`, 15, yPos);
  doc.setFont(undefined, 'normal');
  
  // Business Trips Table
  yPos += 10;
  doc.setFontSize(12);
  doc.setTextColor(navyBlue[0], navyBlue[1], navyBlue[2]);
  doc.text("Business Trips", 15, yPos);
  
  const businessTrips = filteredTrips.filter(t => t.purpose === "Business");
  
  const tableData = businessTrips.map(trip => [
    trip.date,
    trip.startTimeLocal,
    trip.endTimeLocal,
    trip.distanceMiles.toFixed(2),
    trip.notes || "-",
  ]);
  
  autoTable(doc, {
    startY: yPos + 5,
    head: [["Date", "Start Time", "End Time", "Miles", "Notes"]],
    body: tableData,
    theme: "striped",
    headStyles: {
      fillColor: navyBlue,
      textColor: [255, 255, 255],
      fontSize: 10,
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [245, 247, 250],
    },
    styles: {
      fontSize: 9,
      textColor: darkGrey,
    },
    columnStyles: {
      0: { cellWidth: 30 },
      1: { cellWidth: 30 },
      2: { cellWidth: 30 },
      3: { cellWidth: 25 },
      4: { cellWidth: 'auto' },
    },
  });
  
  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(grey[0], grey[1], grey[2]);
    doc.text(
      "Generated by MilesFocus • AI-Focus Technologies",
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
  }
  
  // Save the PDF
  const filename = `MilesFocus-IRS-Report-${month || "All"}-${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
}
